let boxs=document.querySelectorAll(".box");
let nqypn=document.querySelector(".nqypn");
let winsec=document.querySelector(".winsec");
let cellimg=document.querySelector(".cellimg");

let a1q=document.querySelector("#a1");
let a2q=document.querySelector("#a2");
let a3q=document.querySelector("#a3");
let a4q=document.querySelector("#a4");
let a5q=document.querySelector("#a5");
let a6q=document.querySelector("#a6");
let a7q=document.querySelector("#a7");
let a8q=document.querySelector("#a8");
let b1q=document.querySelector("#b1");
let b2q=document.querySelector("#b2");
let b3q=document.querySelector("#b3");
let b4q=document.querySelector("#b4");
let b5q=document.querySelector("#b5");
let b6q=document.querySelector("#b6");
let b7q=document.querySelector("#b7");
let b8q=document.querySelector("#b8");
let c1q=document.querySelector("#c1");
let c2q=document.querySelector("#c2");
let c3q=document.querySelector("#c3");
let c4q=document.querySelector("#c4");
let c5q=document.querySelector("#c5");
let c6q=document.querySelector("#c6");
let c7q=document.querySelector("#c7");
let c8q=document.querySelector("#c8");
let d1q=document.querySelector("#d1");
let d2q=document.querySelector("#d2");
let d3q=document.querySelector("#d3");
let d4q=document.querySelector("#d4");
let d5q=document.querySelector("#d5");
let d6q=document.querySelector("#d6");
let d7q=document.querySelector("#d7");
let d8q=document.querySelector("#d8");
let e1q=document.querySelector("#e1");
let e2q=document.querySelector("#e2");
let e3q=document.querySelector("#e3");
let e4q=document.querySelector("#e4");
let e5q=document.querySelector("#e5");
let e6q=document.querySelector("#e6");
let e7q=document.querySelector("#e7");
let e8q=document.querySelector("#e8");
let f1q=document.querySelector("#f1");
let f2q=document.querySelector("#f2");
let f3q=document.querySelector("#f3");
let f4q=document.querySelector("#f4");
let f5q=document.querySelector("#f5");
let f6q=document.querySelector("#f6");
let f7q=document.querySelector("#f7");
let f8q=document.querySelector("#f8");
let g1q=document.querySelector("#g1");
let g2q=document.querySelector("#g2");
let g3q=document.querySelector("#g3");
let g4q=document.querySelector("#g4");
let g5q=document.querySelector("#g5");
let g6q=document.querySelector("#g6");
let g7q=document.querySelector("#g7");
let g8q=document.querySelector("#g8");
let h1q=document.querySelector("#h1");
let h2q=document.querySelector("#h2");
let h3q=document.querySelector("#h3");
let h4q=document.querySelector("#h4");
let h5q=document.querySelector("#h5");
let h6q=document.querySelector("#h6");
let h7q=document.querySelector("#h7");
let h8q=document.querySelector("#h8");

let not=document.querySelector(".notification");

let na1=0;
let na2=0;
let na3=0;
let na4=0;
let na5=0;
let na6=0;
let na7=0;
let na8=0;
let nb1=0;
let nb2=0;
let nb3=0;
let nb4=0;
let nb5=0;
let nb6=0;
let nb7=0;
let nb8=0;
let nc1=0;
let nc2=0;
let nc3=0;
let nc4=0;
let nc5=0;
let nc6=0;
let nc7=0;
let nc8=0;
let nd1=0;
let nd2=0;
let nd3=0;
let nd4=0;
let nd5=0;
let nd6=0;
let nd7=0;
let nd8=0;
let ne1=0;
let ne2=0;
let ne3=0;
let ne4=0;
let ne5=0;
let ne6=0;
let ne7=0;
let ne8=0;
let nf1=0;
let nf2=0;
let nf3=0;
let nf4=0;
let nf5=0;
let nf6=0;
let nf7=0;
let nf8=0;
let ng1=0;
let ng2=0;
let ng3=0;
let ng4=0;
let ng5=0;
let ng6=0;
let ng7=0;
let ng8=0;
let nh1=0;
let nh2=0;
let nh3=0;
let nh4=0;
let nh5=0;
let nh6=0;
let nh7=0;
let nh8=0;

let va1=0;
let va2=0;
let va3=0;
let va4=0;
let va5=0;
let va6=0;
let va7=0;
let va8=0;
let vb1=0;
let vb2=0;
let vb3=0;
let vb4=0;
let vb5=0;
let vb6=0;
let vb7=0;
let vb8=0;
let vc1=0;
let vc2=0;
let vc3=0;
let vc4=0;
let vc5=0;
let vc6=0;
let vc7=0;
let vc8=0;
let vd1=0;
let vd2=0;
let vd3=0;
let vd4=0;
let vd5=0;
let vd6=0;
let vd7=0;
let vd8=0;
let ve1=0;
let ve2=0;
let ve3=0;
let ve4=0;
let ve5=0;
let ve6=0;
let ve7=0;
let ve8=0;
let vf1=0;
let vf2=0;
let vf3=0;
let vf4=0;
let vf5=0;
let vf6=0;
let vf7=0;
let vf8=0;
let vg1=0;
let vg2=0;
let vg3=0;
let vg4=0;
let vg5=0;
let vg6=0;
let vg7=0;
let vg8=0;
let vh1=0;
let vh2=0;
let vh3=0;
let vh4=0;
let vh5=0;
let vh6=0;
let vh7=0;
let vh8=0;

let nqp=0;
let n;

function boxa1(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb1=1;
    nc1=1;
    nd1=1;
    ne1=1;
    nf1=1;
    ng1=1;
    nh1=1;
    nb2=1;
    nc3=1;
    nd4=1;
    ne5=1;
    nf6=1;
    ng7=1;
    nh8=1;
}
function boxa2(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb2=1;
    nc2=1;
    nd2=1;
    ne2=1;
    nf2=1;
    ng2=1;
    nh2=1;
    nb1=1;
    nb3=1;
    nc4=1;
    nd5=1;
    ne6=1;
    nf7=1;
    ng8=1;
}
function boxa3(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb3=1;
    nc3=1;
    nd3=1;
    ne3=1;
    nf3=1;
    ng3=1;
    nh3=1;
    nb2=1;
    nc1=1;
    nb4=1;
    nc5=1;
    nd6=1;
    ne7=1;
    nf8=1;
}
function boxa4(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb4=1;
    nc4=1;
    nd4=1;
    ne4=1;
    nf4=1;
    ng4=1;
    nh4=1;
    nb3=1;
    nc2=1;
    nd1=1;
    nb5=1;
    nc6=1;
    nd7=1;
    ne8=1;
}
function boxa5(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb5=1;
    nc5=1;
    nd5=1;
    ne5=1;
    nf5=1;
    ng5=1;
    nh5=1;
    nb4=1;
    nc3=1;
    nd2=1;
    ne1=1;
    nb6=1;
    nc7=1;
    nd8=1;
}
function boxa6(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb6=1;
    nc6=1;
    nd6=1;
    ne6=1;
    nf6=1;
    ng6=1;
    nh6=1;
    nb5=1;
    nc4=1;
    nd3=1;
    ne2=1;
    nf1=1;
    nb7=1;
    nc8=1;
}
function boxa7(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb7=1;
    nc7=1;
    nd7=1;
    ne7=1;
    nf7=1;
    ng7=1;
    nh7=1;
    nb6=1;
    nc5=1;
    nd4=1;
    ne3=1;
    nf2=1;
    ng1=1;
    nb8=1;
}
function boxa8(){
    na1=1;
    na2=1;
    na3=1;
    na4=1;
    na5=1;
    na6=1;
    na7=1;
    na8=1;
    nb8=1;
    nc8=1;
    nd8=1;
    ne8=1;
    nf8=1;
    ng8=1;
    nh8=1;
    nb7=1;
    nc6=1;
    nd5=1;
    ne4=1;
    nf3=1;
    ng2=1;
    nh1=1;
}

function boxb1(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na1=1;
    nc1=1;
    nd1=1;
    ne1=1;
    nf1=1;
    ng1=1;
    nh1=1;
    nc2=1;
    nd3=1;
    ne4=1;
    nf5=1;
    ng6=1;
    nh7=1;
    na2=1;
}
function boxb2(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na2=1;
    nc2=1;
    nd2=1;
    ne2=1;
    nf2=1;
    ng2=1;
    nh2=1;
    na1=1;
    na3=1;
    nc1=1;
    nc3=1;
    nd4=1;
    ne5=1;
    nf6=1;
    ng7=1;
    nh8=1;
}
function boxb3(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na3=1;
    nc3=1;
    nd3=1;
    ne3=1;
    nf3=1;
    ng3=1;
    nh3=1;
    na2=1;
    na4=1;
    nc2=1;
    nd1=1;
    nc4=1;
    nd5=1;
    ne6=1;
    nf7=1;
    ng8=1;
}
function boxb4(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na4=1;
    nc4=1;
    nd4=1;
    ne4=1;
    nf4=1;
    ng4=1;
    nh4=1;
    na3=1;
    na5=1;
    nc3=1;
    nd2=1;
    ne1=1;
    nc5=1;
    nd6=1;
    ne7=1;
    nf8=1;
}
function boxb5(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na5=1;
    nc5=1;
    nd5=1;
    ne5=1;
    nf5=1;
    ng5=1;
    nh5=1;
    na4=1;
    na6=1;
    nc4=1;
    nd3=1;
    ne2=1;
    nf1=1;
    nc6=1;
    nd7=1;
    ne8=1;
}
function boxb6(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na6=1;
    nc6=1;
    nd6=1;
    ne6=1;
    nf6=1;
    ng6=1;
    nh6=1;
    na5=1;
    na7=1;
    nc5=1;
    nd4=1;
    ne3=1;
    nf2=1;
    ng1=1;
    nc7=1;
    nd8=1;
}
function boxb7(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na7=1;
    nc7=1;
    nd7=1;
    ne7=1;
    nf7=1;
    ng7=1;
    nh7=1;
    na6=1;
    na8=1;
    nc6=1;
    nd5=1;
    ne4=1;
    nf3=1;
    ng2=1;
    nh1=1;
    nc8=1;
}
function boxb8(){
    nb1=1;
    nb2=1;
    nb3=1;
    nb4=1;
    nb5=1;
    nb6=1;
    nb7=1;
    nb8=1;
    na8=1;
    nc8=1;
    nd8=1;
    ne8=1;
    nf8=1;
    ng8=1;
    nh8=1;
    na7=1;
    nc7=1;
    nd6=1;
    ne5=1;
    nf4=1;
    ng3=1;
    nh2=1;
}

function boxc1(){
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb1=1;
    na1=1;
    nd1=1;
    ne1=1;
    nf1=1;
    ng1=1;
    nh1=1;
    nb2=1;
    na3=1;
    nd2=1;
    ne3=1;
    nf4=1;
    ng5=1;
    nh6=1;
}
function boxc2(){
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb2=1;
    na2=1;
    nd2=1;
    ne2=1;
    nf2=1;
    ng2=1;
    nh2=1;
    nb1=1;
    nb3=1;
    na4=1;
    nd1=1;
    nd3=1;
    ne4=1;
    nf5=1;
    ng6=1;
    nh7=1;
}
function boxc3(){ 
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb3=1;
    na3=1;
    nd3=1;
    ne3=1;
    nf3=1;
    ng3=1;
    nh3=1;
    nb2=1;
    na1=1;
    nb4=1;
    na5=1;
    nd2=1;
    ne1=1;
    nd4=1;
    ne5=1;
    nf6=1;
    ng7=1;
    nh8=1;
}
function boxc4(){
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb4=1;
    na4=1;
    nd4=1;
    ne4=1;
    nf4=1;
    ng4=1;
    nh4=1;
    nb3=1;
    na2=1;
    nb5=1;
    na6=1;
    nd3=1;
    ne2=1;
    nf1=1;
    nd5=1;
    ne6=1;
    nf7=1;
    ng8=1;
}
function boxc5(){
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb5=1;
    na5=1;
    nd5=1;
    ne5=1;
    nf5=1;
    ng5=1;
    nh5=1;
    nb4=1;
    na3=1;
    nb6=1;
    na7=1;
    nd4=1;
    ne3=1;
    nf2=1;
    ng1=1;
    nd6=1;
    ne7=1;
    nf8=1;
}
function boxc6(){
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb6=1;
    na6=1;
    nd6=1;
    ne6=1;
    nf6=1;
    ng6=1;
    nh6=1;
    nb5=1;
    na4=1;
    nb7=1;
    na8=1;
    nd5=1;
    ne4=1;
    nf3=1;
    ng2=1;
    nh1=1;
    nd7=1;
    ne8=1;
}
function boxc7(){
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb7=1;
    na7=1;
    nd7=1;
    ne7=1;
    nf7=1;
    ng7=1;
    nh7=1;
    nb6=1;
    na5=1;
    nb8=1;
    nd6=1;
    ne5=1;
    nf4=1;
    ng3=1;
    nh2=1;
    nd8=1;
}
function boxc8(){
    nc1=1;
    nc2=1;
    nc3=1;
    nc4=1;
    nc5=1;
    nc6=1;
    nc7=1;
    nc8=1;
    nb8=1;
    na8=1;
    nd8=1;
    ne8=1;
    nf8=1;
    ng8=1;
    nh8=1;
    nb7=1;
    na6=1;
    nd7=1;
    ne6=1;
    nf5=1;
    ng4=1;
    nh3=1;
}

function boxd1(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb1=1;
    nc1=1;
    na1=1;
    ne1=1;
    nf1=1;
    ng1=1;
    nh1=1;
    nc2=1;
    nb3=1;
    na4=1;
    ne2=1;
    nf3=1;
    ng4=1;
    nh5=1;
}
function boxd2(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb2=1;
    nc2=1;
    na2=1;
    ne2=1;
    nf2=1;
    ng2=1;
    nh2=1;
    nc1=1;
    nc3=1;
    nb4=1;
    na5=1;
    ne3=1;
    nf4=1;
    ng5=1;
    nh6=1;
    ne1=1;
}
function boxd3(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb3=1;
    nc3=1;
    na3=1;
    ne3=1;
    nf3=1;
    ng3=1;
    nh3=1;
    nc2=1;
    nb1=1;
    nc4=1;
    nb5=1;
    na6=1;
    ne2=1;
    nf1=1;
    ne4=1;
    nf5=1;
    ng6=1;
    nh7=1;
}
function boxd4(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb4=1;
    nc4=1;
    na4=1;
    ne4=1;
    nf4=1;
    ng4=1;
    nh4=1;
    nc3=1;
    nb2=1;
    na1=1;
    nc5=1;
    nb6=1;
    na7=1;
    ne3=1;
    nf2=1;
    ng1=1;
    ne5=1;
    nf6=1;
    ng7=1;
    nh8=1;
}
function boxd5(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb5=1;
    nc5=1;
    na5=1;
    ne5=1;
    nf5=1;
    ng5=1;
    nh5=1;
    nc4=1;
    nb3=1;
    na2=1;
    nc6=1;
    nb7=1;
    na8=1;
    ne4=1;
    nf3=1;
    ng2=1;
    nh1=1;
    ne6=1;
    nf7=1;
    ng8=1;

}
function boxd6(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb6=1;
    nc6=1;
    nd6=1;
    ne6=1;
    nf6=1;
    ng6=1;
    nh6=1;
    nc5=1;
    nb4=1;
    na3=1;
    nc7=1;
    nb8=1;
    ne5=1;
    nf4=1;
    ng3=1;
    nh2=1;
    ne7=1;
    nf8=1;
}
function boxd7(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb7=1;
    nc7=1;
    na7=1;
    ne7=1;
    nf7=1;
    ng7=1;
    nh7=1;
    nc6=1;
    nb5=1;
    na4=1;
    nc8=1;
    ne8=1;
    ne6=1;
    nf5=1;
    ng4=1;
    nh3=1;
}
function boxd8(){
    nd1=1;
    nd2=1;
    nd3=1;
    nd4=1;
    nd5=1;
    nd6=1;
    nd7=1;
    nd8=1;
    nb8=1;
    nc8=1;
    na8=1;
    ne8=1;
    nf8=1;
    ng8=1;
    nh8=1;
    nc7=1;
    nb6=1;
    na5=1;
    ne7=1;
    nf6=1;
    ng5=1;
    nh4=1;
}

function boxe1(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb1=1;
    nc1=1;
    nd1=1;
    na1=1;
    nf1=1;
    ng1=1;
    nh1=1;
    nd2=1;
    nc3=1;
    nb4=1;
    na5=1;
    nf2=1;
    ng3=1;
    nh4=1;
}
function boxe2(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb2=1;
    nc2=1;
    nd2=1;
    na2=1;
    nf2=1;
    ng2=1;
    nh2=1;
    nd1=1;
    nd3=1;
    nc4=1;
    nb5=1;
    na6=1;
    nf1=1;
    nf3=1;
    ng4=1;
    nh5=1;
}
function boxe3(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb3=1;
    nc3=1;
    nd3=1;
    na3=1;
    nf3=1;
    ng3=1;
    nh3=1;
    nd2=1;
    nc1=1;
    nd4=1;
    nc5=1;
    nb6=1;
    na7=1;
    nf2=1;
    ng1=1;
    nf4=1;
    ng5=1;
    nh6=1;
}
function boxe4(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb4=1;
    nc4=1;
    nd4=1;
    na4=1;
    nf4=1;
    ng4=1;
    nh4=1;
    nd3=1;
    nc2=1;
    nb1=1;
    nd5=1;
    nc6=1;
    nb7=1;
    na8=1;
    nf3=1;
    ng2=1;
    nh1=1;
    nf5=1;
    ng6=1;
    nh7=1;
}
function boxe5(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb5=1;
    nc5=1;
    nd5=1;
    na5=1;
    nf5=1;
    ng5=1;
    nh5=1;
    nd4=1;
    nc3=1;
    nb2=1;
    na1=1;
    nd6=1;
    nc7=1;
    nb8=1;
    nf4=1;
    ng3=1;
    nh2=1;
    nf6=1;
    ng7=1;
    nh8=1;
}
function boxe6(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb6=1;
    nc6=1;
    nd6=1;
    na6=1;
    nf6=1;
    ng6=1;
    nh6=1;
    nd5=1;
    nc4=1;
    nb3=1;
    na2=1;
    nd7=1;
    nf7=1;
    nc8=1;
    ng8=1;
    nf5=1;
    ng4=1;
    nh3=1;
}
function boxe7(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb7=1;
    nc7=1;
    nd7=1;
    na7=1;
    nf7=1;
    ng7=1;
    nh7=1;
    nd6=1;
    nc5=1;
    nb4=1;
    na3=1;
    nd8=1;
    nf6=1;
    ng5=1;
    nh4=1;
    nf8=1;
}
function boxe8(){
    ne1=1;
    ne2=1;
    ne3=1;
    ne4=1;
    ne5=1;
    ne6=1;
    ne7=1;
    ne8=1;
    nb8=1;
    nc8=1;
    nd8=1;
    na8=1;
    nf8=1;
    ng8=1;
    nh8=1;
    nd7=1;
    nc6=1;
    nb5=1;
    na4=1;
    nf7=1;
    ng6=1;
    nh5=1;
}

function boxf1(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb1=1;
    nc1=1;
    nd1=1;
    ne1=1;
    na1=1;
    ng1=1;
    nh1=1;
    ne2=1;
    nd3=1;
    nc4=1;
    nb5=1;
    na6=1;
    ng2=1;
    nh3=1;
}
function boxf2(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb2=1;
    nc2=1;
    nd2=1;
    ne2=1;
    na2=1;
    ng2=1;
    nh2=1;
    ne1=1;
    ne3=1;
    nd4=1;
    nc5=1;
    nb6=1;
    na7=1;
    ng1=1;
    ng3=1;
    nh4=1;
}
function boxf3(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb3=1;
    nc3=1;
    nd3=1;
    ne3=1;
    na3=1;
    ng3=1;
    nh3=1;
    ne2=1;
    nd1=1;
    ne4=1;
    nd5=1;
    nc6=1;
    nb7=1;
    na8=1;
    ng2=1;
    nh1=1;
    ng4=1;
    nh5=1;
}
function boxf4(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb4=1;
    nc4=1;
    nd4=1;
    ne4=1;
    na4=1;
    ng4=1;
    nh4=1;
    ne3=1;
    nd2=1;
    nc1=1;
    ne5=1;
    nd6=1;
    nc7=1;
    nb8=1;
    ng3=1;
    nh2=1;
    ng5=1;
    nh6=1;
}
function boxf5(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb5=1;
    nc5=1;
    nd5=1;
    ne5=1;
    na5=1;
    ng5=1;
    nh5=1;
    ne4=1;
    nd3=1;
    nc2=1;
    nb1=1;
    ne6=1;
    nd7=1;
    nc8=1;
    ng4=1;
    nh3=1;
    ng6=1;
    nh7=1;
}
function boxf6(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb6=1;
    nc6=1;
    nd6=1;
    ne6=1;
    na6=1;
    ng6=1;
    nh6=1;
    ne5=1;
    nd4=1;
    nc3=1;
    nb2=1;
    na1=1;
    ne7=1;
    nd8=1;
    ng5=1;
    nh4=1;
    ng7=1;
    nh8=1;
}
function boxf7(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb7=1;
    nc7=1;
    nd7=1;
    ne7=1;
    na7=1;
    ng7=1;
    nh7=1;
    ne6=1;
    nd5=1;
    nc4=1;
    nb3=1;
    na2=1;
    ne8=1;
    nh5=1;
    ng6=1;
    ng8=1;
}
function boxf8(){
    nf1=1;
    nf2=1;
    nf3=1;
    nf4=1;
    nf5=1;
    nf6=1;
    nf7=1;
    nf8=1;
    nb8=1;
    nc8=1;
    nd8=1;
    ne8=1;
    na8=1;
    ng8=1;
    nh8=1;
    ne7=1;
    nd6=1;
    nc5=1;
    nb4=1;
    na3=1;
    ng7=1;
    nh6=1;
}

function boxg1(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb1=1;
    nc1=1;
    nd1=1;
    ne1=1;
    nf1=1;
    na1=1;
    nh1=1;
    nf2=1;
    ne3=1;
    nd4=1;
    nc5=1;
    nb6=1;
    na7=1;
    nh2=1;
}
function boxg2(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb2=1;
    nc2=1;
    nd2=1;
    ne2=1;
    nf2=1;
    na2=1;
    nh2=1;
    nf1=1;
    nf3=1;
    ne4=1;
    nd5=1;
    nc6=1;
    nb7=1;
    na8=1;
    nh3=1;
    nh1=1;
}
function boxg3(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb3=1;
    nc3=1;
    nd3=1;
    ne3=1;
    nf3=1;
    na3=1;
    nh3=1;
    nf2=1;
    ne1=1;
    nf4=1;
    ne5=1;
    nd6=1;
    nc7=1;
    nb8=1;
    nh2=1;
    nh4=1;
}
function boxg4(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb4=1;
    nc4=1;
    nd4=1;
    ne4=1;
    nf4=1;
    na4=1;
    nh4=1;
    nf3=1;
    ne2=1;
    nd1=1;
    nf5=1;
    ne6=1;
    nd7=1;
    nc8=1;
    nh3=1;
    nh5=1;
}
function boxg5(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb5=1;
    nc5=1;
    nd5=1;
    ne5=1;
    nf5=1;
    na5=1;
    nh5=1;
    nf4=1;
    ne3=1;
    nd2=1;
    nc1=1;
    nf6=1;
    ne7=1;
    nd8=1;
    nh4=1;
    nh6=1;
}
function boxg6(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb6=1;
    nc6=1;
    nd6=1;
    ne6=1;
    nf6=1;
    na6=1;
    nh6=1;
    nf5=1;
    ne4=1;
    nd3=1;
    nc2=1;
    nb1=1;
    nf7=1;
    ne8=1;
    nh5=1;
    nh7=1;
}
function boxg7(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb7=1;
    nc7=1;
    nd7=1;
    ne7=1;
    nf7=1;
    na7=1;
    nh7=1;
    nf6=1;
    ne5=1;
    nd4=1;
    nc3=1;
    nb2=1;
    na1=1;
    nf8=1;
    nh6=1;
    nh8=1;
}
function boxg8(){
    ng1=1;
    ng2=1;
    ng3=1;
    ng4=1;
    ng5=1;
    ng6=1;
    ng7=1;
    ng8=1;
    nb8=1;
    nc8=1;
    nd8=1;
    ne8=1;
    nf8=1;
    na8=1;
    nh8=1;
    nf7=1;
    ne6=1;
    nd5=1;
    nc4=1;
    nb3=1;
    na2=1;
    nh7=1;
}

function boxh1(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb1=1;
    nc1=1;
    nd1=1;
    ne1=1;
    nf1=1;
    ng1=1;
    na1=1;
    ng2=1;
    nf3=1;
    ne4=1;
    nd5=1;
    nc6=1;
    nb7=1;
    na8=1;
}
function boxh2(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb2=1;
    nc2=1;
    nd2=1;
    ne2=1;
    nf2=1;
    ng2=1;
    na2=1;
    ng1=1;
    ng3=1;
    nf4=1;
    ne5=1;
    nd6=1;
    nc7=1;
    nb8=1;
}
function boxh3(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb3=1;
    nc3=1;
    nd3=1;
    ne3=1;
    nf3=1;
    ng3=1;
    na3=1;
    ng2=1;
    nf1=1;
    ng4=1;
    nf5=1;
    ne6=1;
    nd7=1;
    nc8=1;
}
function boxh4(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb4=1;
    nc4=1;
    nd4=1;
    ne4=1;
    nf4=1;
    ng4=1;
    na4=1;
    ng3=1;
    nf2=1;
    ne1=1;
    ng5=1;
    nf6=1;
    ne7=1;
    nd8=1;
}
function boxh5(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb5=1;
    nc5=1;
    nd5=1;
    ne5=1;
    nf5=1;
    ng5=1;
    na5=1;
    ng4=1;
    nf3=1;
    ne2=1;
    nd1=1;
    ng6=1;
    nf7=1;
    ne8=1;
}
function boxh6(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb6=1;
    nc6=1;
    nd6=1;
    ne6=1;
    nf6=1;
    ng6=1;
    na6=1;
    ng5=1;
    nf4=1;
    ne3=1;
    nd2=1;
    nc1=1;
    ng7=1;
    nf8=1;
}
function boxh7(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb7=1;
    nc7=1;
    nd7=1;
    ne7=1;
    nf7=1;
    ng7=1;
    na7=1;
    ng6=1;
    nf5=1;
    ne4=1;
    nd3=1;
    nc2=1;
    nb1=1;
    ng8=1;
}
function boxh8(){
    nh1=1;
    nh2=1;
    nh3=1;
    nh4=1;
    nh5=1;
    nh6=1;
    nh7=1;
    nh8=1;
    nb8=1;
    nc8=1;
    nd8=1;
    ne8=1;
    nf8=1;
    ng8=1;
    na8=1;
    ng7=1;
    nf6=1;
    ne5=1;
    nd4=1;
    nc3=1;
    nb2=1;
    na1=1;
}





function boxa1opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb1=0;
    nc1=0;
    nd1=0;
    ne1=0;
    nf1=0;
    ng1=0;
    nh1=0;
    nb2=0;
    nc3=0;
    nd4=0;
    ne5=0;
    nf6=0;
    ng7=0;
    nh8=0;
}
function boxa2opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb2=0;
    nc2=0;
    nd2=0;
    ne2=0;
    nf2=0;
    ng2=0;
    nh2=0;
    nb1=0;
    nb3=0;
    nc4=0;
    nd5=0;
    ne6=0;
    nf7=0;
    ng8=0;
}
function boxa3opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb3=0;
    nc3=0;
    nd3=0;
    ne3=0;
    nf3=0;
    ng3=0;
    nh3=0;
    nb2=0;
    nc1=0;
    nb4=0;
    nc5=0;
    nd6=0;
    ne7=0;
    nf8=0;
}
function boxa4opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb4=0;
    nc4=0;
    nd4=0;
    ne4=0;
    nf4=0;
    ng4=0;
    nh4=0;
    nb3=0;
    nc2=0;
    nd1=0;
    nb5=0;
    nc6=0;
    nd7=0;
    ne8=0;
}
function boxa5opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb5=0;
    nc5=0;
    nd5=0;
    ne5=0;
    nf5=0;
    ng5=0;
    nh5=0;
    nb4=0;
    nc3=0;
    nd2=0;
    ne1=0;
    nb6=0;
    nc7=0;
    nd8=0;
}
function boxa6opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb6=0;
    nc6=0;
    nd6=0;
    ne6=0;
    nf6=0;
    ng6=0;
    nh6=0;
    nb5=0;
    nc4=0;
    nd3=0;
    ne2=0;
    nf1=0;
    nb7=0;
    nc8=0;
}
function boxa7opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb7=0;
    nc7=0;
    nd7=0;
    ne7=0;
    nf7=0;
    ng7=0;
    nh7=0;
    nb6=0;
    nc5=0;
    nd4=0;
    ne3=0;
    nf2=0;
    ng1=0;
    nb8=0;
}
function boxa8opp(){
    na1=0;
    na2=0;
    na3=0;
    na4=0;
    na5=0;
    na6=0;
    na7=0;
    na8=0;
    nb8=0;
    nc8=0;
    nd8=0;
    ne8=0;
    nf8=0;
    ng8=0;
    nh8=0;
    nb7=0;
    nc6=0;
    nd5=0;
    ne4=0;
    nf3=0;
    ng2=0;
    nh1=0;
}

function boxb1opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na1=0;
    nc1=0;
    nd1=0;
    ne1=0;
    nf1=0;
    ng1=0;
    nh1=0;
    nc2=0;
    nd3=0;
    ne4=0;
    nf5=0;
    ng6=0;
    nh7=0;
    na2=0;
}
function boxb2opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na2=0;
    nc2=0;
    nd2=0;
    ne2=0;
    nf2=0;
    ng2=0;
    nh2=0;
    na1=0;
    na3=0;
    nc1=0;
    nc3=0;
    nd4=0;
    ne5=0;
    nf6=0;
    ng7=0;
    nh8=0;
}
function boxb3opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na3=0;
    nc3=0;
    nd3=0;
    ne3=0;
    nf3=0;
    ng3=0;
    nh3=0;
    na2=0;
    na4=0;
    nc2=0;
    nd1=0;
    nc4=0;
    nd5=0;
    ne6=0;
    nf7=0;
    ng8=0;
}
function boxb4opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na4=0;
    nc4=0;
    nd4=0;
    ne4=0;
    nf4=0;
    ng4=0;
    nh4=0;
    na3=0;
    na5=0;
    nc3=0;
    nd2=0;
    ne1=0;
    nc5=0;
    nd6=0;
    ne7=0;
    nf8=0;
}
function boxb5opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na5=0;
    nc5=0;
    nd5=0;
    ne5=0;
    nf5=0;
    ng5=0;
    nh5=0;
    na4=0;
    na6=0;
    nc4=0;
    nd3=0;
    ne2=0;
    nf1=0;
    nc6=0;
    nd7=0;
    ne8=0;
}
function boxb6opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na6=0;
    nc6=0;
    nd6=0;
    ne6=0;
    nf6=0;
    ng6=0;
    nh6=0;
    na5=0;
    na7=0;
    nc5=0;
    nd4=0;
    ne3=0;
    nf2=0;
    ng1=0;
    nc7=0;
    nd8=0;
}
function boxb7opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na7=0;
    nc7=0;
    nd7=0;
    ne7=0;
    nf7=0;
    ng7=0;
    nh7=0;
    na6=0;
    na8=0;
    nc6=0;
    nd5=0;
    ne4=0;
    nf3=0;
    ng2=0;
    nh1=0;
    nc8=0;
}
function boxb8opp(){
    nb1=0;
    nb2=0;
    nb3=0;
    nb4=0;
    nb5=0;
    nb6=0;
    nb7=0;
    nb8=0;
    na8=0;
    nc8=0;
    nd8=0;
    ne8=0;
    nf8=0;
    ng8=0;
    nh8=0;
    na7=0;
    nc7=0;
    nd6=0;
    ne5=0;
    nf4=0;
    ng3=0;
    nh2=0;
}

function boxc1opp(){
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb1=0;
    na1=0;
    nd1=0;
    ne1=0;
    nf1=0;
    ng1=0;
    nh1=0;
    nb2=0;
    na3=0;
    nd2=0;
    ne3=0;
    nf4=0;
    ng5=0;
    nh6=0;
}
function boxc2opp(){
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb2=0;
    na2=0;
    nd2=0;
    ne2=0;
    nf2=0;
    ng2=0;
    nh2=0;
    nb1=0;
    nb3=0;
    na4=0;
    nd1=0;
    nd3=0;
    ne4=0;
    nf5=0;
    ng6=0;
    nh7=0;
}
function boxc3opp(){ 
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb3=0;
    na3=0;
    nd3=0;
    ne3=0;
    nf3=0;
    ng3=0;
    nh3=0;
    nb2=0;
    na1=0;
    nb4=0;
    na5=0;
    nd2=0;
    ne1=0;
    nd4=0;
    ne5=0;
    nf6=0;
    ng7=0;
    nh8=0;
}
function boxc4opp(){
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb4=0;
    na4=0;
    nd4=0;
    ne4=0;
    nf4=0;
    ng4=0;
    nh4=0;
    nb3=0;
    na2=0;
    nb5=0;
    na6=0;
    nd3=0;
    ne2=0;
    nf1=0;
    nd5=0;
    ne6=0;
    nf7=0;
    ng8=0;
}
function boxc5opp(){
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb5=0;
    na5=0;
    nd5=0;
    ne5=0;
    nf5=0;
    ng5=0;
    nh5=0;
    nb4=0;
    na3=0;
    nb6=0;
    na7=0;
    nd4=0;
    ne3=0;
    nf2=0;
    ng1=0;
    nd6=0;
    ne7=0;
    nf8=0;
}
function boxc6opp(){
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb6=0;
    na6=0;
    nd6=0;
    ne6=0;
    nf6=0;
    ng6=0;
    nh6=0;
    nb5=0;
    na4=0;
    nb7=0;
    na8=0;
    nd5=0;
    ne4=0;
    nf3=0;
    ng2=0;
    nh1=0;
    nd7=0;
    ne8=0;
}
function boxc7opp(){
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb7=0;
    na7=0;
    nd7=0;
    ne7=0;
    nf7=0;
    ng7=0;
    nh7=0;
    nb6=0;
    na5=0;
    nb8=0;
    nd6=0;
    ne5=0;
    nf4=0;
    ng3=0;
    nh2=0;
    nd8=0;
}
function boxc8opp(){
    nc1=0;
    nc2=0;
    nc3=0;
    nc4=0;
    nc5=0;
    nc6=0;
    nc7=0;
    nc8=0;
    nb8=0;
    na8=0;
    nd8=0;
    ne8=0;
    nf8=0;
    ng8=0;
    nh8=0;
    nb7=0;
    na6=0;
    nd7=0;
    ne6=0;
    nf5=0;
    ng4=0;
    nh3=0;
}

function boxd1opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb1=0;
    nc1=0;
    na1=0;
    ne1=0;
    nf1=0;
    ng1=0;
    nh1=0;
    nc2=0;
    nb3=0;
    na4=0;
    ne2=0;
    nf3=0;
    ng4=0;
    nh5=0;
}
function boxd2opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb2=0;
    nc2=0;
    na2=0;
    ne2=0;
    nf2=0;
    ng2=0;
    nh2=0;
    nc1=0;
    nc3=0;
    nb4=0;
    na5=0;
    ne3=0;
    nf4=0;
    ng5=0;
    nh6=0;
    ne1=0;
}
function boxd3opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb3=0;
    nc3=0;
    na3=0;
    ne3=0;
    nf3=0;
    ng3=0;
    nh3=0;
    nc2=0;
    nb1=0;
    nc4=0;
    nb5=0;
    na6=0;
    ne2=0;
    nf1=0;
    ne4=0;
    nf5=0;
    ng6=0;
    nh7=0;
}
function boxd4opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb4=0;
    nc4=0;
    na4=0;
    ne4=0;
    nf4=0;
    ng4=0;
    nh4=0;
    nc3=0;
    nb2=0;
    na1=0;
    nc5=0;
    nb6=0;
    na7=0;
    ne3=0;
    nf2=0;
    ng1=0;
    ne5=0;
    nf6=0;
    ng7=0;
    nh8=0;
}
function boxd5opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb5=0;
    nc5=0;
    na5=0;
    ne5=0;
    nf5=0;
    ng5=0;
    nh5=0;
    nc4=0;
    nb3=0;
    na2=0;
    nc6=0;
    nb7=0;
    na8=0;
    ne4=0;
    nf3=0;
    ng2=0;
    nh1=0;
    ne6=0;
    nf7=0;
    ng8=0;

}
function boxd6opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb6=0;
    nc6=0;
    nd6=0;
    ne6=0;
    nf6=0;
    ng6=0;
    nh6=0;
    nc5=0;
    nb4=0;
    na3=0;
    nc7=0;
    nb8=0;
    ne5=0;
    nf4=0;
    ng3=0;
    nh2=0;
    ne7=0;
    nf8=0;
}
function boxd7opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb7=0;
    nc7=0;
    na7=0;
    ne7=0;
    nf7=0;
    ng7=0;
    nh7=0;
    nc6=0;
    nb5=0;
    na4=0;
    nc8=0;
    ne8=0;
    ne6=0;
    nf5=0;
    ng4=0;
    nh3=0;
}
function boxd8opp(){
    nd1=0;
    nd2=0;
    nd3=0;
    nd4=0;
    nd5=0;
    nd6=0;
    nd7=0;
    nd8=0;
    nb8=0;
    nc8=0;
    na8=0;
    ne8=0;
    nf8=0;
    ng8=0;
    nh8=0;
    nc7=0;
    nb6=0;
    na5=0;
    ne7=0;
    nf6=0;
    ng5=0;
    nh4=0;
}

function boxe1opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb1=0;
    nc1=0;
    nd1=0;
    na1=0;
    nf1=0;
    ng1=0;
    nh1=0;
    nd2=0;
    nc3=0;
    nb4=0;
    na5=0;
    nf2=0;
    ng3=0;
    nh4=0;
}
function boxe2opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb2=0;
    nc2=0;
    nd2=0;
    na2=0;
    nf2=0;
    ng2=0;
    nh2=0;
    nd1=0;
    nd3=0;
    nc4=0;
    nb5=0;
    na6=0;
    nf1=0;
    nf3=0;
    ng4=0;
    nh5=0;
}
function boxe3opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb3=0;
    nc3=0;
    nd3=0;
    na3=0;
    nf3=0;
    ng3=0;
    nh3=0;
    nd2=0;
    nc1=0;
    nd4=0;
    nc5=0;
    nb6=0;
    na7=0;
    nf2=0;
    ng1=0;
    nf4=0;
    ng5=0;
    nh6=0;
}
function boxe4opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb4=0;
    nc4=0;
    nd4=0;
    na4=0;
    nf4=0;
    ng4=0;
    nh4=0;
    nd3=0;
    nc2=0;
    nb1=0;
    nd5=0;
    nc6=0;
    nb7=0;
    na8=0;
    nf3=0;
    ng2=0;
    nh1=0;
    nf5=0;
    ng6=0;
    nh7=0;
}
function boxe5opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb5=0;
    nc5=0;
    nd5=0;
    na5=0;
    nf5=0;
    ng5=0;
    nh5=0;
    nd4=0;
    nc3=0;
    nb2=0;
    na1=0;
    nd6=0;
    nc7=0;
    nb8=0;
    nf4=0;
    ng3=0;
    nh2=0;
    nf6=0;
    ng7=0;
    nh8=0;
}
function boxe6opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb6=0;
    nc6=0;
    nd6=0;
    na6=0;
    nf6=0;
    ng6=0;
    nh6=0;
    nd5=0;
    nc4=0;
    nb3=0;
    na2=0;
    nd7=0;
    nf7=0;
    nc8=0;
    ng8=0;
    nf5=0;
    ng4=0;
    nh3=0;
}
function boxe7opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb7=0;
    nc7=0;
    nd7=0;
    na7=0;
    nf7=0;
    ng7=0;
    nh7=0;
    nd6=0;
    nc5=0;
    nb4=0;
    na3=0;
    nd8=0;
    nf6=0;
    ng5=0;
    nh4=0;
    nf8=0;
}
function boxe8opp(){
    ne1=0;
    ne2=0;
    ne3=0;
    ne4=0;
    ne5=0;
    ne6=0;
    ne7=0;
    ne8=0;
    nb8=0;
    nc8=0;
    nd8=0;
    na8=0;
    nf8=0;
    ng8=0;
    nh8=0;
    nd7=0;
    nc6=0;
    nb5=0;
    na4=0;
    nf7=0;
    ng6=0;
    nh5=0;
}

function boxf1opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb1=0;
    nc1=0;
    nd1=0;
    ne1=0;
    na1=0;
    ng1=0;
    nh1=0;
    ne2=0;
    nd3=0;
    nc4=0;
    nb5=0;
    na6=0;
    ng2=0;
    nh3=0;
}
function boxf2opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb2=0;
    nc2=0;
    nd2=0;
    ne2=0;
    na2=0;
    ng2=0;
    nh2=0;
    ne1=0;
    ne3=0;
    nd4=0;
    nc5=0;
    nb6=0;
    na7=0;
    ng1=0;
    ng3=0;
    nh4=0;
}
function boxf3opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb3=0;
    nc3=0;
    nd3=0;
    ne3=0;
    na3=0;
    ng3=0;
    nh3=0;
    ne2=0;
    nd1=0;
    ne4=0;
    nd5=0;
    nc6=0;
    nb7=0;
    na8=0;
    ng2=0;
    nh1=0;
    ng4=0;
    nh5=0;
}
function boxf4opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb4=0;
    nc4=0;
    nd4=0;
    ne4=0;
    na4=0;
    ng4=0;
    nh4=0;
    ne3=0;
    nd2=0;
    nc1=0;
    ne5=0;
    nd6=0;
    nc7=0;
    nb8=0;
    ng3=0;
    nh2=0;
    ng5=0;
    nh6=0;
}
function boxf5opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb5=0;
    nc5=0;
    nd5=0;
    ne5=0;
    na5=0;
    ng5=0;
    nh5=0;
    ne4=0;
    nd3=0;
    nc2=0;
    nb1=0;
    ne6=0;
    nd7=0;
    nc8=0;
    ng4=0;
    nh3=0;
    ng6=0;
    nh7=0;
}
function boxf6opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb6=0;
    nc6=0;
    nd6=0;
    ne6=0;
    na6=0;
    ng6=0;
    nh6=0;
    ne5=0;
    nd4=0;
    nc3=0;
    nb2=0;
    na1=0;
    ne7=0;
    nd8=0;
    ng5=0;
    nh4=0;
    ng7=0;
    nh8=0;
}
function boxf7opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb7=0;
    nc7=0;
    nd7=0;
    ne7=0;
    na7=0;
    ng7=0;
    nh7=0;
    ne6=0;
    nd5=0;
    nc4=0;
    nb3=0;
    na2=0;
    ne8=0;
    nh5=0;
    ng6=0;
    ng8=0;
}
function boxf8opp(){
    nf1=0;
    nf2=0;
    nf3=0;
    nf4=0;
    nf5=0;
    nf6=0;
    nf7=0;
    nf8=0;
    nb8=0;
    nc8=0;
    nd8=0;
    ne8=0;
    na8=0;
    ng8=0;
    nh8=0;
    ne7=0;
    nd6=0;
    nc5=0;
    nb4=0;
    na3=0;
    ng7=0;
    nh6=0;
}

function boxg1opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb1=0;
    nc1=0;
    nd1=0;
    ne1=0;
    nf1=0;
    na1=0;
    nh1=0;
    nf2=0;
    ne3=0;
    nd4=0;
    nc5=0;
    nb6=0;
    na7=0;
    nh2=0;
}
function boxg2opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb2=0;
    nc2=0;
    nd2=0;
    ne2=0;
    nf2=0;
    na2=0;
    nh2=0;
    nf1=0;
    nf3=0;
    ne4=0;
    nd5=0;
    nc6=0;
    nb7=0;
    na8=0;
    nh3=0;
    nh1=0;
}
function boxg3opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb3=0;
    nc3=0;
    nd3=0;
    ne3=0;
    nf3=0;
    na3=0;
    nh3=0;
    nf2=0;
    ne1=0;
    nf4=0;
    ne5=0;
    nd6=0;
    nc7=0;
    nb8=0;
    nh2=0;
    nh4=0;
}
function boxg4opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb4=0;
    nc4=0;
    nd4=0;
    ne4=0;
    nf4=0;
    na4=0;
    nh4=0;
    nf3=0;
    ne2=0;
    nd1=0;
    nf5=0;
    ne6=0;
    nd7=0;
    nc8=0;
    nh3=0;
    nh5=0;
}
function boxg5opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb5=0;
    nc5=0;
    nd5=0;
    ne5=0;
    nf5=0;
    na5=0;
    nh5=0;
    nf4=0;
    ne3=0;
    nd2=0;
    nc1=0;
    nf6=0;
    ne7=0;
    nd8=0;
    nh4=0;
    nh6=0;
}
function boxg6opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb6=0;
    nc6=0;
    nd6=0;
    ne6=0;
    nf6=0;
    na6=0;
    nh6=0;
    nf5=0;
    ne4=0;
    nd3=0;
    nc2=0;
    nb1=0;
    nf7=0;
    ne8=0;
    nh5=0;
    nh7=0;
}
function boxg7opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb7=0;
    nc7=0;
    nd7=0;
    ne7=0;
    nf7=0;
    na7=0;
    nh7=0;
    nf6=0;
    ne5=0;
    nd4=0;
    nc3=0;
    nb2=0;
    na1=0;
    nf8=0;
    nh6=0;
    nh8=0;
}
function boxg8opp(){
    ng1=0;
    ng2=0;
    ng3=0;
    ng4=0;
    ng5=0;
    ng6=0;
    ng7=0;
    ng8=0;
    nb8=0;
    nc8=0;
    nd8=0;
    ne8=0;
    nf8=0;
    na8=0;
    nh8=0;
    nf7=0;
    ne6=0;
    nd5=0;
    nc4=0;
    nb3=0;
    na2=0;
    nh7=0;
}

function boxh1opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb1=0;
    nc1=0;
    nd1=0;
    ne1=0;
    nf1=0;
    ng1=0;
    na1=0;
    ng2=0;
    nf3=0;
    ne4=0;
    nd5=0;
    nc6=0;
    nb7=0;
    na8=0;
}
function boxh2opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb2=0;
    nc2=0;
    nd2=0;
    ne2=0;
    nf2=0;
    ng2=0;
    na2=0;
    ng1=0;
    ng3=0;
    nf4=0;
    ne5=0;
    nd6=0;
    nc7=0;
    nb8=0;
}
function boxh3opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb3=0;
    nc3=0;
    nd3=0;
    ne3=0;
    nf3=0;
    ng3=0;
    na3=0;
    ng2=0;
    nf1=0;
    ng4=0;
    nf5=0;
    ne6=0;
    nd7=0;
    nc8=0;
}
function boxh4opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb4=0;
    nc4=0;
    nd4=0;
    ne4=0;
    nf4=0;
    ng4=0;
    na4=0;
    ng3=0;
    nf2=0;
    ne1=0;
    ng5=0;
    nf6=0;
    ne7=0;
    nd8=0;
}
function boxh5opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb5=0;
    nc5=0;
    nd5=0;
    ne5=0;
    nf5=0;
    ng5=0;
    na5=0;
    ng4=0;
    nf3=0;
    ne2=0;
    nd1=0;
    ng6=0;
    nf7=0;
    ne8=0;
}
function boxh6opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb6=0;
    nc6=0;
    nd6=0;
    ne6=0;
    nf6=0;
    ng6=0;
    na6=0;
    ng5=0;
    nf4=0;
    ne3=0;
    nd2=0;
    nc1=0;
    ng7=0;
    nf8=0;
}
function boxh7opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb7=0;
    nc7=0;
    nd7=0;
    ne7=0;
    nf7=0;
    ng7=0;
    na7=0;
    ng6=0;
    nf5=0;
    ne4=0;
    nd3=0;
    nc2=0;
    nb1=0;
    ng8=0;
}
function boxh8opp(){
    nh1=0;
    nh2=0;
    nh3=0;
    nh4=0;
    nh5=0;
    nh6=0;
    nh7=0;
    nh8=0;
    nb8=0;
    nc8=0;
    nd8=0;
    ne8=0;
    nf8=0;
    ng8=0;
    na8=0;
    ng7=0;
    nf6=0;
    ne5=0;
    nd4=0;
    nc3=0;
    nb2=0;
    na1=0;
}

function clearnumber(){
    if(va1==1){
        boxa1();
    }
    if(va2==1){
        boxa2();
    }
    if(va3==1){
        boxa3();
    }
    if(va4==1){
        boxa4();
    }
    if(va5==1){
        boxa5();
    }
    if(va6==1){
        boxa6();
    }
    if(va7==1){
        boxa7();
    }
    if(va8==1){
        boxa8();
    }
    if(vb1==1){
        boxb1();
    }
    if(vb2==1){
        boxb2();
    }
    if(vb3==1){
        boxb3();
    }
    if(vb4==1){
        boxb4();
    }
    if(vb5==1){
        boxb5();
    }
    if(vb6==1){
        boxb6();
    }
    if(vb7==1){
        boxb7();
    }
    if(vb8==1){
        boxb8();
    }
    if(vc1==1){
        boxc1();
    }
    if(vc2==1){
        boxc2();
    }
    if(vc3==1){
        boxc3();
    }
    if(vc4==1){
        boxc4();
    }
    if(vc5==1){
        boxc5();
    }
    if(vc6==1){
        boxc6();
    }
    if(vc7==1){
        boxc7();
    }
    if(vc8==1){
        boxc8();
    }
    if(vd1==1){
        boxd1();
    }
    if(vd2==1){
        boxd2();
    }
    if(vd3==1){
        boxd3();
    }
    if(vd4==1){
        boxd4();
    }
    if(vd5==1){
        boxd5();
    }
    if(vd6==1){
        boxd6();
    }
    if(vd7==1){
        boxd7();
    }
    if(vd8==1){
        boxd8();
    }
    if(ve1==1){
        boxe1();
    }
    if(ve2==1){
        boxe2();
    }
    if(ve3==1){
        boxe3();
    }
    if(ve4==1){
        boxe4();
    }
    if(ve5==1){
        boxe5();
    }
    if(ve6==1){
        boxe6();
    }
    if(ve7==1){
        boxe7();
    }
    if(ve8==1){
        boxe8();
    }
    if(vf1==1){
        boxf1();
    }
    if(vf2==1){
        boxf2();
    }
    if(vf3==1){
        boxf3();
    }
    if(vf4==1){
        boxf4();
    }
    if(vf5==1){
        boxf5();
    }
    if(vf6==1){
        boxf6();
    }
    if(vf7==1){
        boxf7();
    }
    if(vf8==1){
        boxf8();
    }
    if(vg1==1){
        boxg1();
    }
    if(vg2==1){
        boxg2();
    }
    if(vg3==1){
        boxg3();
    }
    if(vg4==1){
        boxg4();
    }
    if(vg5==1){
        boxg5();
    }
    if(vg6==1){
        boxg6();
    }
    if(vg7==1){
        boxg7();
    }
    if(vg8==1){
        boxg8();
    }
    if(vh1==1){
        boxh1();
    }
    if(vh2==1){
        boxh2();
    }
    if(vh3==1){
        boxh3();
    }
    if(vh4==1){
        boxh4();
    }
    if(vh5==1){
        boxh5();
    }
    if(vh6==1){
        boxh6();
    }
    if(vh7==1){
        boxh7();
    }
    if(vh8==1){
        boxh8();
    }
}

function numqueenpl(){
    nqp=0;
    if(va1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(va2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(va3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(va4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(va5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(va6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(va7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(va8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vb8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vc8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vd8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(ve8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vf8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vg8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh1==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh2==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh3==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh4==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh5==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh6==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh7==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if(vh8==1){
        nqp++;
        let n = nqp;
        nqypn.innerHTML=n;
    }
    if((va1==0)&&(va2==0)&&(va3==0)&&(va4==0)&&(va5==0)&&(va6==0)&&(va7==0)&&(va8==0)&&
       (vb1==0)&&(vb2==0)&&(vb3==0)&&(vb4==0)&&(vb5==0)&&(vb6==0)&&(vb7==0)&&(vb8==0)&&
       (vc1==0)&&(vc2==0)&&(vc3==0)&&(vc4==0)&&(vc5==0)&&(vc6==0)&&(vc7==0)&&(vc8==0)&&
       (vd1==0)&&(vd2==0)&&(vd3==0)&&(vd4==0)&&(vd5==0)&&(vd6==0)&&(vd7==0)&&(vd8==0)&&
       (ve1==0)&&(ve2==0)&&(ve3==0)&&(ve4==0)&&(ve5==0)&&(ve6==0)&&(ve7==0)&&(ve8==0)&&
       (vf1==0)&&(vf2==0)&&(vf3==0)&&(vf4==0)&&(vf5==0)&&(vf6==0)&&(vf7==0)&&(vf8==0)&&
       (vg1==0)&&(vg2==0)&&(vg3==0)&&(vg4==0)&&(vg5==0)&&(vg6==0)&&(vg7==0)&&(vg8==0)&&
       (vh1==0)&&(vh2==0)&&(vh3==0)&&(vh4==0)&&(vh5==0)&&(vh6==0)&&(vh7==0)&&(vh8==0)){
        let n = 0;
        nqypn.innerHTML=n;
       }
}

function clearall(){
 na1=0;
 na2=0;
 na3=0;
 na4=0;
 na5=0;
 na6=0;
 na7=0;
 na8=0;
 nb1=0;
 nb2=0;
 nb3=0;
 nb4=0;
 nb5=0;
 nb6=0;
 nb7=0;
 nb8=0;
 nc1=0;
 nc2=0;
 nc3=0;
 nc4=0;
 nc5=0;
 nc6=0;
 nc7=0;
 nc8=0;
 nd1=0;
 nd2=0;
 nd3=0;
 nd4=0;
 nd5=0;
 nd6=0;
 nd7=0;
 nd8=0;
 ne1=0;
 ne2=0;
 ne3=0;
 ne4=0;
 ne5=0;
 ne6=0;
 ne7=0;
 ne8=0;
 nf1=0;
 nf2=0;
 nf3=0;
 nf4=0;
 nf5=0;
 nf6=0;
 nf7=0;
 nf8=0;
 ng1=0;
 ng2=0;
 ng3=0;
 ng4=0;
 ng5=0;
 ng6=0;
 ng7=0;
 ng8=0;
 nh1=0;
 nh2=0;
 nh3=0;
 nh4=0;
 nh5=0;
 nh6=0;
 nh7=0;
 nh8=0;

 va1=0;
 va2=0;
 va3=0;
 va4=0;
 va5=0;
 va6=0;
 va7=0;
 va8=0;
 vb1=0;
 vb2=0;
 vb3=0;
 vb4=0;
 vb5=0;
 vb6=0;
 vb7=0;
 vb8=0;
 vc1=0;
 vc2=0;
 vc3=0;
 vc4=0;
 vc5=0;
 vc6=0;
 vc7=0;
 vc8=0;
 vd1=0;
 vd2=0;
 vd3=0;
 vd4=0;
 vd5=0;
 vd6=0;
 vd7=0;
 vd8=0;
 ve1=0;
 ve2=0;
 ve3=0;
 ve4=0;
 ve5=0;
 ve6=0;
 ve7=0;
 ve8=0;
 vf1=0;
 vf2=0;
 vf3=0;
 vf4=0;
 vf5=0;
 vf6=0;
 vf7=0;
 vf8=0;
 vg1=0;
 vg2=0;
 vg3=0;
 vg4=0;
 vg5=0;
 vg6=0; 
 vg7=0;
 vg8=0;
 vh1=0;
 vh2=0;
 vh3=0;
 vh4=0;
 vh5=0;
 vh6=0;
 vh7=0;
 vh8=0;

 a1q.style.backgroundImage="none";
 a2q.style.backgroundImage="none";
 a3q.style.backgroundImage="none";
 a4q.style.backgroundImage="none";
 a5q.style.backgroundImage="none";
 a6q.style.backgroundImage="none";
 a7q.style.backgroundImage="none";
 a8q.style.backgroundImage="none";

 b1q.style.backgroundImage="none";
 b2q.style.backgroundImage="none";
 b3q.style.backgroundImage="none";
 b4q.style.backgroundImage="none";
 b5q.style.backgroundImage="none";
 b6q.style.backgroundImage="none";
 b7q.style.backgroundImage="none";
 b8q.style.backgroundImage="none";

 c1q.style.backgroundImage="none";
 c2q.style.backgroundImage="none";
 c3q.style.backgroundImage="none";
 c4q.style.backgroundImage="none";
 c5q.style.backgroundImage="none";
 c6q.style.backgroundImage="none";
 c7q.style.backgroundImage="none";
 c8q.style.backgroundImage="none";

 d1q.style.backgroundImage="none";
 d2q.style.backgroundImage="none";
 d3q.style.backgroundImage="none";
 d4q.style.backgroundImage="none";
 d5q.style.backgroundImage="none";
 d6q.style.backgroundImage="none";
 d7q.style.backgroundImage="none";
 d8q.style.backgroundImage="none";

 e1q.style.backgroundImage="none";
 e2q.style.backgroundImage="none";
 e3q.style.backgroundImage="none";
 e4q.style.backgroundImage="none";
 e5q.style.backgroundImage="none";
 e6q.style.backgroundImage="none";
 e7q.style.backgroundImage="none";
 e8q.style.backgroundImage="none";

 f1q.style.backgroundImage="none";
 f2q.style.backgroundImage="none";
 f3q.style.backgroundImage="none";
 f4q.style.backgroundImage="none";
 f5q.style.backgroundImage="none";
 f6q.style.backgroundImage="none";
 f7q.style.backgroundImage="none";
 f8q.style.backgroundImage="none";

 g1q.style.backgroundImage="none";
 g2q.style.backgroundImage="none";
 g3q.style.backgroundImage="none";
 g4q.style.backgroundImage="none";
 g5q.style.backgroundImage="none";
 g6q.style.backgroundImage="none";
 g7q.style.backgroundImage="none";
 g8q.style.backgroundImage="none";

 h1q.style.backgroundImage="none";
 h2q.style.backgroundImage="none";
 h3q.style.backgroundImage="none";
 h4q.style.backgroundImage="none";
 h5q.style.backgroundImage="none";
 h6q.style.backgroundImage="none";
 h7q.style.backgroundImage="none";
 h8q.style.backgroundImage="none";

 nqp=0;
 nqypn.innerHTML=0;

}

function win(){
    if(nqp==8){
        winsec.style.backgroundColor="rgba(161,159,159,0.5)";
        winsec.style.border="2px solid black";
        winsec.innerHTML="You won the Game"
        cellimg.style.backgroundImage="url('cellebration.png')";
    }
    else{
        winsec.innerHTML=null;
        winsec.style.backgroundColor="transparent";
        winsec.style.border="none";
    }
}

boxs.forEach((boxid)=>{
    boxid.addEventListener("click",()=>{
        let id=boxid.getAttribute("id");
        console.log(id);
        if(id=='a1'){
            if(na1==0){
                va1=1;
                a1q.style.backgroundImage="url('crown1.jpg')";
                boxa1();
                numqueenpl();
            }
            else{
                va1=0;
                a1q.style.backgroundImage="none";
                boxa1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='a2'){
            if(na2==0){
                va2=1;
                a2q.style.backgroundImage="url('crown1.jpg')";
                boxa2();
                numqueenpl();
            }
            else{
                va2=0;
                a2q.style.backgroundImage="none";
                boxa2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='a3'){
            if(na3==0){
                va3=1;
                a3q.style.backgroundImage="url('crown1.jpg')";
                boxa3();
                numqueenpl();
            }
            else{
                va3=0;
                a3q.style.backgroundImage="none";
                boxa3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='a4'){
            if(na4==0){
                va4=1;
                a4q.style.backgroundImage="url('crown1.jpg')";
                boxa4();
                numqueenpl();
            }
            else{
                va4=0;
                a4q.style.backgroundImage="none";
                boxa4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='a5'){
            if(na5==0){
                va5=1;
                a5q.style.backgroundImage="url('crown1.jpg')";
                boxa5();
                numqueenpl();
            }
            else{
                va5=0;
                a5q.style.backgroundImage="none";
                boxa5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='a6'){
            if(na6==0){
                va6=1;
                a6q.style.backgroundImage="url('crown1.jpg')";
                boxa6();
                numqueenpl();
            }
            else{
                va6=0;
                a6q.style.backgroundImage="none";
                boxa6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='a7'){
            if(na7==0){
                va7=1;
                a7q.style.backgroundImage="url('crown1.jpg')";
                boxa7();
                numqueenpl();
            }
            else{
                va7=0;
                a7q.style.backgroundImage="none";
                boxa7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='a8'){
            if(na8==0){
                va8=1;
                a8q.style.backgroundImage="url('crown1.jpg')";
                boxa8();
                numqueenpl();
            }
            else{
                va8=0;
                a8q.style.backgroundImage="none";
                boxa8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b1'){
            if(nb1==0){
                vb1=1;
                b1q.style.backgroundImage="url('crown1.jpg')";
                boxb1();
                numqueenpl();
            }
            else{
                vb1=0;
                b1q.style.backgroundImage="none";
                boxb1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b2'){
            if(nb2==0){
                vb2=1;
                b2q.style.backgroundImage="url('crown1.jpg')";
                boxb2();
                numqueenpl();
            }
            else{
                vb2=0;
                b2q.style.backgroundImage="none";
                boxb2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b3'){
            if(nb3==0){
                vb3=1;
                b3q.style.backgroundImage="url('crown1.jpg')";
                boxb3();
                numqueenpl();
            }
            else{
                vb3=0;
                b3q.style.backgroundImage="none";
                boxb3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b4'){
            if(nb4==0){
                vb4=1;
                b4q.style.backgroundImage="url('crown1.jpg')";
                boxb4();
                numqueenpl();
            }
            else{
                vb4=0;
                b4q.style.backgroundImage="none";
                boxb4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b5'){
            if(nb5==0){
                vb5=1;
                b5q.style.backgroundImage="url('crown1.jpg')";
                boxb5();
                numqueenpl();
            }
            else{
                vb5=0;
                b5q.style.backgroundImage="none";
                boxb5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b6'){
            if(nb6==0){
                vb6=1;
                b6q.style.backgroundImage="url('crown1.jpg')";
                boxb6();
                numqueenpl();
            }
            else{
                vb6=0;
                b6q.style.backgroundImage="none";
                boxb6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b7'){
            if(nb7==0){
                vb7=1;
                b7q.style.backgroundImage="url('crown1.jpg')";
                boxb7();
                numqueenpl();
            }
            else{
                vb7=0;
                b7q.style.backgroundImage="none";
                boxb7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='b8'){
            if(nb8==0){
                vb8=1;
                b8q.style.backgroundImage="url('crown1.jpg')";
                boxb8();
                numqueenpl();
            }
            else{
                vb8=0;
                b8q.style.backgroundImage="none";
                boxb8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c1'){
            if(nc1==0){
                vc1=1;
                c1q.style.backgroundImage="url('crown1.jpg')";
                boxc1();
                numqueenpl();
            }
            else{
                vc1=0;
                c1q.style.backgroundImage="none";
                boxc1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c2'){
            if(nc2==0){
                vc2=1;
                c2q.style.backgroundImage="url('crown1.jpg')";
                boxc2();
                numqueenpl();
            }
            else{
                vc2=0;
                c2q.style.backgroundImage="none";
                boxc2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c3'){
            if(nc3==0){
                vc3=1;
                c3q.style.backgroundImage="url('crown1.jpg')";
                boxc3();
                numqueenpl();
            }
            else{
                vc3=0;
                c3q.style.backgroundImage="none";
                boxc3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c4'){
            if(nc4==0){
                vc4=1;
                c4q.style.backgroundImage="url('crown1.jpg')";
                boxc4();
                numqueenpl();
            }
            else{
                vc4=0;
                c4q.style.backgroundImage="none";
                boxc4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c5'){
            if(nc5==0){
                vc5=1;
                c5q.style.backgroundImage="url('crown1.jpg')";
                boxc5();
                numqueenpl();
            }
            else{
                vc5=0;
                c5q.style.backgroundImage="none";
                boxc5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c6'){
            if(nc6==0){
                vc6=1;
                c6q.style.backgroundImage="url('crown1.jpg')";
                boxc6();
                numqueenpl();
            }
            else{
                vc6=0;
                c6q.style.backgroundImage="none";
                boxc6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c7'){
            if(nc7==0){
                vc7=1;
                c7q.style.backgroundImage="url('crown1.jpg')";
                boxc7();
                numqueenpl();
            }
            else{
                vc7=0;
                c7q.style.backgroundImage="none";
                boxc7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='c8'){
            if(nc8==0){
                vc8=1;
                c8q.style.backgroundImage="url('crown1.jpg')";
                boxc8();
                numqueenpl();
            }
            else{
                vc8=0;
                c8q.style.backgroundImage="none";
                boxc8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d1'){
            if(nd1==0){
                vd1=1;
                d1q.style.backgroundImage="url('crown1.jpg')";
                boxd1();
                numqueenpl();
            }
            else{
                vd1=0;
                d1q.style.backgroundImage="none";
                boxd1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d2'){
            if(nd2==0){
                vd2=1;
                d2q.style.backgroundImage="url('crown1.jpg')";
                boxd2();
                numqueenpl();
            }
            else{
                vd2=0;
                d2q.style.backgroundImage="none";
                boxd2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d3'){
            if(nd3==0){
                vd3=1;
                d3q.style.backgroundImage="url('crown1.jpg')";
                boxd3();
                numqueenpl();
            }
            else{
                vd3=0;
                d3q.style.backgroundImage="none";
                boxd3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d4'){
            if(nd4==0){
                vd4=1;
                d4q.style.backgroundImage="url('crown1.jpg')";
                boxd4();
                numqueenpl();
            }
            else{
                vd4=0;
                d4q.style.backgroundImage="none";
                boxd4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d5'){
            if(nd5==0){
                vd5=1;
                d5q.style.backgroundImage="url('crown1.jpg')";
                boxd5();
                numqueenpl();
            }
            else{
                vd5=0;
                d5q.style.backgroundImage="none";
                boxd5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d6'){
            if(nd6==0){
                vd6=1;
                d6q.style.backgroundImage="url('crown1.jpg')";
                boxd6();
                numqueenpl();
            }
            else{
                vd6=0;
                d6q.style.backgroundImage="none";
                boxd6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d7'){
            if(nd7==0){
                vd7=1;
                d7q.style.backgroundImage="url('crown1.jpg')";
                boxd7();
                numqueenpl();
            }
            else{
                vd7=0;
                d7q.style.backgroundImage="none";
                boxd7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='d8'){
            if(nd8==0){
                vd8=1;
                d8q.style.backgroundImage="url('crown1.jpg')";
                boxd8();
                numqueenpl();
            }
            else{
                vd8=0;
                d8q.style.backgroundImage="none";
                boxd8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e1'){
            if(ne1==0){
                ve1=1;
                e1q.style.backgroundImage="url('crown1.jpg')";
                boxe1();
                numqueenpl();
            }
            else{
                ve1=0;
                e1q.style.backgroundImage="none";
                boxe1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e2'){
            if(ne2==0){
                ve2=1;
                e2q.style.backgroundImage="url('crown1.jpg')";
                boxe2();
                numqueenpl();
            }
            else{
                ve2=0;
                e2q.style.backgroundImage="none";
                boxe2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e3'){
            if(ne3==0){
                ve3=1;
                e3q.style.backgroundImage="url('crown1.jpg')";
                boxe3();
                numqueenpl();
            }
            else{
                ve3=0;
                e3q.style.backgroundImage="none";
                boxe3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e4'){
            if(ne4==0){
                ve4=1;
                e4q.style.backgroundImage="url('crown1.jpg')";
                boxe4();
                numqueenpl();
            }
            else{
                ve4=0;
                e4q.style.backgroundImage="none";
                boxe4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e5'){
            if(ne5==0){
                ve5=1;
                e5q.style.backgroundImage="url('crown1.jpg')";
                boxe5();
                numqueenpl();
            }
            else{
                ve5=0;
                e5q.style.backgroundImage="none";
                boxe5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e6'){
            if(ne6==0){
                ve6=1;
                e6q.style.backgroundImage="url('crown1.jpg')";
                boxe6();
                numqueenpl();
            }
            else{
                ve6=0;
                e6q.style.backgroundImage="none";
                boxe6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e7'){
            if(ne7==0){
                ve7=1;
                e7q.style.backgroundImage="url('crown1.jpg')";
                boxe7();
                numqueenpl();
            }
            else{
                ve7=0;
                e7q.style.backgroundImage="none";
                boxe7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='e8'){
            if(ne8==0){
                ve8=1;
                e8q.style.backgroundImage="url('crown1.jpg')";
                boxe8();
                numqueenpl();
            }
            else{
                ve8=0;
                e8q.style.backgroundImage="none";
                boxe8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f1'){
            if(nf1==0){
                vf1=1;
                f1q.style.backgroundImage="url('crown1.jpg')";
                boxf1();
                numqueenpl();
            }
            else{
                vf1=0;
                f1q.style.backgroundImage="none";
                boxf1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f2'){
            if(nf2==0){
                vf2=1;
                f2q.style.backgroundImage="url('crown1.jpg')";
                boxf2();
                numqueenpl();
            }
            else{
                vf2=0;
                f2q.style.backgroundImage="none";
                boxf2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f3'){
            if(nf3==0){
                vf3=1;
                f3q.style.backgroundImage="url('crown1.jpg')";
                boxf3();
                numqueenpl();
            }
            else{
                vf3=0;
                f3q.style.backgroundImage="none";
                boxf3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f4'){
            if(nf4==0){
                vf4=1;
                f4q.style.backgroundImage="url('crown1.jpg')";
                boxf4();
                numqueenpl();
            }
            else{
                vf4=0;
                f4q.style.backgroundImage="none";
                boxf4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f5'){
            if(nf5==0){
                vf5=1;
                f5q.style.backgroundImage="url('crown1.jpg')";
                boxf5();
                numqueenpl();
            }
            else{
                vf5=0;
                f5q.style.backgroundImage="none";
                boxf5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f6'){
            if(nf6==0){
                vf6=1;
                f6q.style.backgroundImage="url('crown1.jpg')";
                boxf6();
                numqueenpl();
            }
            else{
                vf6=0;
                f6q.style.backgroundImage="none";
                boxf6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f7'){
            if(nf7==0){
                vf7=1;
                f7q.style.backgroundImage="url('crown1.jpg')";
                boxf7();
                numqueenpl();
            }
            else{
                vf7=0;
                f7q.style.backgroundImage="none";
                boxf7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='f8'){
            if(nf8==0){
                vf8=1;
                f8q.style.backgroundImage="url('crown1.jpg')";
                boxf8();
                numqueenpl();
            }
            else{
                vf8=0;
                f8q.style.backgroundImage="none";
                boxf8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g1'){
            if(ng1==0){
                vg1=1;
                g1q.style.backgroundImage="url('crown1.jpg')";
                boxg1();
                numqueenpl();
            }
            else{
                vg1=0;
                g1q.style.backgroundImage="none";
                boxg1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g2'){
            if(ng2==0){
                vg2=1;
                g2q.style.backgroundImage="url('crown1.jpg')";
                boxg2();
                numqueenpl();
            }
            else{
                vg2=0;
                g2q.style.backgroundImage="none";
                boxg2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g3'){
            if(ng3==0){
                vg3=1;
                g3q.style.backgroundImage="url('crown1.jpg')";
                boxg3();
                numqueenpl();
            }
            else{
                vg3=0;
                g3q.style.backgroundImage="none";
                boxg3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g4'){
            if(ng4==0){
                vg4=1;
                g4q.style.backgroundImage="url('crown1.jpg')";
                boxg4();
                numqueenpl();
            }
            else{
                vg4=0;
                g4q.style.backgroundImage="none";
                boxg4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g5'){
            if(ng5==0){
                vg5=1;
                g5q.style.backgroundImage="url('crown1.jpg')";
                boxg5();
                numqueenpl();
            }
            else{
                vg5=0;
                g5q.style.backgroundImage="none";
                boxg5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g6'){
            if(ng6==0){
                vg6=1;
                g6q.style.backgroundImage="url('crown1.jpg')";
                boxg6();
                numqueenpl();
            }
            else{
                vg6=0;
                g6q.style.backgroundImage="none";
                boxg6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g7'){
            if(ng7==0){
                vg7=1;
                g7q.style.backgroundImage="url('crown1.jpg')";
                boxg7();
                numqueenpl();
            }
            else{
                vg7=0;
                g7q.style.backgroundImage="none";
                boxg7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='g8'){
            if(ng8==0){
                vg8=1;
                g8q.style.backgroundImage="url('crown1.jpg')";
                boxg8();
                numqueenpl();
            }
            else{
                vg8=0;
                g8q.style.backgroundImage="none";
                boxg8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h1'){
            if(nh1==0){
                vh1=1;
                h1q.style.backgroundImage="url('crown1.jpg')";
                boxh1();
                numqueenpl();
            }
            else{
                vh1=0;
                h1q.style.backgroundImage="none";
                boxh1opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h2'){
            if(nh2==0){
                vh2=1;
                h2q.style.backgroundImage="url('crown1.jpg')";
                boxh2();
                numqueenpl();
            }
            else{
                vh2=0;
                h2q.style.backgroundImage="none";
                boxh2opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h3'){
            if(nh3==0){
                vh3=1;
                h3q.style.backgroundImage="url('crown1.jpg')";
                boxh3();
                numqueenpl();
            }
            else{
                vh3=0;
                h3q.style.backgroundImage="none";
                boxh3opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h4'){
            if(nh4==0){
                vh4=1;
                h4q.style.backgroundImage="url('crown1.jpg')";
                boxh4();
                numqueenpl();
            }
            else{
                vh4=0;
                h4q.style.backgroundImage="none";
                boxh4opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h5'){
            if(nh5==0){
                vh5=1;
                h5q.style.backgroundImage="url('crown1.jpg')";
                boxh5();
                numqueenpl();
            }
            else{
                vh5=0;
                h5q.style.backgroundImage="none";
                boxh5opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h6'){
            if(nh6==0){
                vh6=1;
                h6q.style.backgroundImage="url('crown1.jpg')";
                boxh6();
                numqueenpl();
            }
            else{
                vh6=0;
                h6q.style.backgroundImage="none";
                boxh6opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h7'){
            if(nh7==0){
                vh7=1;
                h7q.style.backgroundImage="url('crown1.jpg')";
                boxh7();
                numqueenpl();
            }
            else{
                vh7=0;
                h7q.style.backgroundImage="none";
                boxh7opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='h8'){   
            if(nh8==0){
                vh8=1;
                h8q.style.backgroundImage="url('crown1.jpg')";
                boxh8();
                numqueenpl();
            }
            else{
                vh8=0;
                h8q.style.backgroundImage="none";
                boxh8opp();
                clearnumber();
                numqueenpl();
            }
        }
        if(id=='ca'){
            console.log("Clear All");
            clearall(); 
        }
        win();
    })
})